name: Build documentation

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  env_var: ${{ vars.ENV_CONTEXT_VAR }}

permissions:
  id-token: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Echo variables
        run: echo "INSTANCE=$INSTANCE"

      - name: Build docs using Writerside Docker builder
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: ${{ vars.INSTANCE }}
          artifact: ${{ vars.ARTIFACT }}
          docker-version: ${{ vars.DOCKER_VERSION }}

      - name: Save artifact with build results
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: |
            artifacts/${{vars.ARTIFACT}}
            artifacts/report.json
            artifacts/${{secrets.ALGOLIA_ARTIFACT}}
          retention-days: 7
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: docs
          path: artifacts

      - name: Test documentation
        uses: JetBrains/writerside-checker-action@v1
        with:
          instance: ${{vars.INSTANCE}}
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: docs

      - name: Unzip artifact
        run: unzip -O UTF-8 -qq '${{vars.ARTIFACT}}' -d dir

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Package and upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dir

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
  publish-indexes:
    needs: [build, test, deploy]
    runs-on: ubuntu-latest
    container:
      image: registry.jetbrains.team/p/writerside/builder/algolia-publisher:2.0.32-3
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: docs
      - name: Unzip artifact
        run: |
          unzip -O UTF-8 -qq '${{secrets.ALGOLIA_ARTIFACT}}' -d algolia-indexes
          env algolia-key='${{secrets.ALGOLIA_WRITE_KEY}}' java -jar /opt/builder/help-publication-agent.jar \
          update-index \
          --application-name '${{secrets.ALGOLIA_APP_ID}}' \
          --index-name '${{secrets.ALGOLIA_INDEX_NAME}}' \
          --product '${{vars.CONFIG_JSON_PRODUCT}}' \
          --version '${{vars.CONFIG_JSON_VERSION}}' \
          --index-directory algolia-indexes/ \
          2>&1 | tee algolia-update-index-log.txt